- public/index.html
> [ci/#1] 제목 변경

- src/App.js
> [test/#10] api key 확인

- src/App.js
> [Fix/#12] kakao redirect시 화면 설정

- src/App.js
> [Fix/#16] 상태 초기화

- src/App.js
- src/components/login/KakaoRedirect.js
> [Tese/#19] redirect 라우트 설정

- src/App.js
- src/components/main/MainContents.js
- src/components/main/buttons/UploadBtn.js
- src/index.js
- src/pages/Main.js
> [Feat/#22] 성적표 파일 업로드

- src/components/main/MainContents.js
- src/components/main/buttons/ChattingBtn.css
- src/components/main/buttons/ChattingBtn.js
- src/components/main/buttons/EditBtn.css
- src/components/main/buttons/EditBtn.js
> [Feat/#24] 성적표 수정 기능

- src/components/main/buttons/UploadBtn.js
> [Fix/#27] 성적표 업로드 API 연결

- src/App.js
- src/components/main/buttons/UploadBtn.js
- src/pages/Main.js
> [Refactor/#29] 로그 정리

- src/components/main/buttons/EditBtn.js
- src/components/main/buttons/UploadBtn.js
> [Fix/#31] 파일 업로드 API 연결

- src/App.js
- src/components/chat/ChatElem.css
- src/components/chat/ChatElem.js
- src/components/chat/QuestionList.css
- src/components/chat/QuestionList.js
- src/components/chat/index.js
- src/components/main/buttons/ChattingBtn.css
- src/components/main/buttons/ChattingBtn.js
- src/pages/Chat.js
> [Feat/#26] 챗봇 기능

- src/components/login/KakaoRedirect.js
- src/components/main/buttons/EditBtn.js
- src/components/main/buttons/UploadBtn.js
- src/pages/Chat.js
> [Fix/#34] api 수정

- src/App.js
- src/components/login/KakaoRedirect.js
> [Feat/#37] 로그인 토큰 localstorage에 저장

- src/App.js
- src/components/login/KakaoRedirect.js
> [Feat/#38] 성적표 유무에 따라 화면 이동

- src/App.js
- src/components/login/KakaoRedirect.js
> [Fix/#41] 성적표 유무에 따라 화면 이동

- src/components/login/KakaoRedirect.js
> [Fix/#43] 오타 수정

- src/components/chat/ChatElem.js
- src/components/chat/QuestionList.js
> [Fix/#46] 챗봇 대화 수정

- src/components/chat/QuestionList.js
> [Fix/#56] 질문 API 연결 오타 수정

- src/components/header/Modal.js
- src/components/header/ModalContent.js
> [Update/#51] 도움말 팝업 내용 수정

- src/components/header/Header.css
> [Feat/#53] 이전 페이지 이동 기능

- src/components/header/EditModal.js
- src/components/header/Modal.js
- src/components/header/UploadModal.js
- src/components/main/buttons/EditBtn.js
- src/components/main/buttons/UploadBtn.js
> [Feat/#50] 파일 업로드 후 팝업 기능

- src/components/chat/ChatElem.js
- src/components/chat/QuestionList.js
> [Feat/#55] 답변 로딩 중일 때 동적 효과 기능
